#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <sys/random.h>
#include <string.h>

// Context structure passed to each worker thread
typedef struct {
    unsigned char *buffer;  // pointer to the target buffer
    size_t length;          // number of bytes to generate
    int depth;              // recursion depth
} WorkerCtx;

#define MAX_DEPTH 4      // limit recursive thread creation
#define SMALL_CHUNK 32   // below this size we stop splitting

// get a single random bit using getrandom
static int random_bit() {
    unsigned char b;
    if (getrandom(&b, 1, 0) != 1) {
        perror("getrandom");
        exit(EXIT_FAILURE);
    }
    return b & 1;
}

// Base case: fill the buffer sequentially
static void fill_random(unsigned char *buf, size_t len) {
    if (getrandom(buf, len, 0) != (ssize_t)len) {
        perror("getrandom");
        exit(EXIT_FAILURE);
    }
}

// Worker function implementing the recursive, threaded algorithm
static void *hexentropy_worker(void *arg) {
    WorkerCtx ctx = *(WorkerCtx *)arg; // copy context

    // Base case: small chunk or depth limit
    if (ctx.length <= SMALL_CHUNK || ctx.depth >= MAX_DEPTH) {
        fill_random(ctx.buffer, ctx.length);
        return NULL;
    }

    pthread_t t1, t2;
    size_t left_len, right_len, mid;

    if (ctx.length % 2 == 0) {
        // Even case: toss the coin first, then split (n-1)/2 recursively
        left_len = (ctx.length - 1) / 2;
        right_len = ctx.length - 1 - left_len;
        mid = left_len;
    } else {
        // Odd case: mid is exactly at n/2
        left_len = ctx.length / 2;
        right_len = ctx.length - left_len - 1;
        mid = left_len;
    }

    // Store the pilouface result at the middle position
    ctx.buffer[mid] = random_bit() ? 0x07 : 0x00;

    // Prepare contexts for both halves
    WorkerCtx left = { ctx.buffer, left_len, ctx.depth + 1 };
    WorkerCtx right = { ctx.buffer + mid + 1, right_len, ctx.depth + 1 };

    // Launch worker threads
    pthread_create(&t1, NULL, hexentropy_worker, &left);
    pthread_create(&t2, NULL, hexentropy_worker, &right);

    pthread_join(t1, NULL);
    pthread_join(t2, NULL);
    return NULL;
}

int main(int argc, char *argv[]) {
    size_t n = 64; // default length if none provided
    if (argc > 1) {
        n = strtoul(argv[1], NULL, 10);
        if (n == 0) {
            fprintf(stderr, "Invalid length\n");
            return EXIT_FAILURE;
        }
    }

    unsigned char *buffer = malloc(n);
    if (!buffer) {
        perror("malloc");
        return EXIT_FAILURE;
    }

    WorkerCtx root = { buffer, n, 0 };
    hexentropy_worker(&root); // start in current thread

    // print the generated bytes in hex form
    for (size_t i = 0; i < n; ++i) {
        printf("%02x", buffer[i]);
    }
    printf("\n");

    free(buffer);
    return 0;
}

