#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <sys/random.h>
#include <string.h>

// Context structure passed to each worker thread
typedef struct {
    unsigned char *buffer;  // pointer to the target buffer
    size_t length;          // number of bytes to generate
    int depth;              // recursion depth
} WorkerCtx;

#define MAX_DEPTH 4      // limit recursive thread creation
#define SMALL_CHUNK 32   // below this size we stop splitting

// get a single random bit using getrandom
static int random_bit() {
    unsigned char b;
    if (getrandom(&b, 1, 0) != 1) {
        perror("getrandom");
        exit(EXIT_FAILURE);
    }
    return b & 1;
}

// Base case: fill the buffer sequentially
static void fill_random(unsigned char *buf, size_t len) {
    if (getrandom(buf, len, 0) != (ssize_t)len) {
        perror("getrandom");
        exit(EXIT_FAILURE);
    }
}

// Worker function implementing the recursive, threaded algorithm
static void *hexentropy_worker(void *arg) {
    WorkerCtx ctx = *(WorkerCtx *)arg; // copy context

    if (ctx.length <= SMALL_CHUNK || ctx.depth >= MAX_DEPTH) {
        fill_random(ctx.buffer, ctx.length);
        return NULL;
    }

    size_t half = ctx.length / 2;
    pthread_t t1, t2;
    WorkerCtx *children = malloc(2 * sizeof(*children));
    if (!children) {
        perror("malloc");
        exit(EXIT_FAILURE);
    }
    WorkerCtx *left = &children[0];
    WorkerCtx *right = &children[1];
    *left = (WorkerCtx){ ctx.buffer, half, ctx.depth + 1 };
    *right = (WorkerCtx){ ctx.buffer + half + (ctx.length % 2), half, ctx.depth + 1 };

    // launch worker threads for both halves
    pthread_create(&t1, NULL, hexentropy_worker, left);
    pthread_create(&t2, NULL, hexentropy_worker, right);

    // odd length: set middle byte using a coin flip (0x00 or 0x07)
    if (ctx.length % 2) {
        ctx.buffer[half] = random_bit() ? 0x07 : 0x00;
    }

    pthread_join(t1, NULL);
    pthread_join(t2, NULL);
    free(children);
    return NULL;
}

int main(int argc, char *argv[]) {
    size_t n = 64; // default length if none provided
    if (argc > 1) {
        n = strtoul(argv[1], NULL, 10);
        if (n == 0) {
            fprintf(stderr, "Invalid length\n");
            return EXIT_FAILURE;
        }
    }

    unsigned char *buffer = malloc(n);
    if (!buffer) {
        perror("malloc");
        return EXIT_FAILURE;
    }

    WorkerCtx root = { buffer, n, 0 };
    hexentropy_worker(&root); // start in current thread

    // print the generated bytes in hex form
    for (size_t i = 0; i < n; ++i) {
        printf("%02x", buffer[i]);
    }
    printf("\n");

    free(buffer);
    return 0;
}

